server:
  port: 8080

spring:
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置,dev环境
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点
  datasource:
    url: jdbc:mysql:///spring_boot_demo?characterEncoding=UTF-8&useUnicode=true
    type: com.alibaba.druid.pool.DruidDataSource
    username: demo
    password: demo123
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: development
logging:
  config: classpath:log/logback-spring.xml
  path: F:\\logs\\springBootDemo
  file: F:\\logs\\springBootDemo\\demo.log